<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('ingredients')->insert([
            // === Kategori 1: Daging & Ikan ===
            [
                'name' => 'Daging Sapi Segar',
                'slug' => 'daging-sapi-segar',
                'unit_id' => 1,
                'category_id' => 1,
                'supplier_id' => 1,
                'price_per_unit' => 120000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Daging Ayam Fillet',
                'slug' => 'daging-ayam-fillet',
                'unit_id' => 1,
                'category_id' => 1,
                'supplier_id' => 2,
                'price_per_unit' => 65000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ikan Kembung',
                'slug' => 'ikan-kembung',
                'unit_id' => 1,
                'category_id' => 1,
                'supplier_id' => 3,
                'price_per_unit' => 55000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Udang Kupas',
                'slug' => 'udang-kupas',
                'unit_id' => 1,
                'category_id' => 1,
                'supplier_id' => 4,
                'price_per_unit' => 90000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Daging Cincang',
                'slug' => 'daging-cincang',
                'unit_id' => 1,
                'category_id' => 1,
                'supplier_id' => 5,
                'price_per_unit' => 95000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === Kategori 2: Sayuran ===
            [
                'name' => 'Wortel',
                'slug' => 'wortel',
                'unit_id' => 1,
                'category_id' => 2,
                'supplier_id' => 6,
                'price_per_unit' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Brokoli',
                'slug' => 'brokoli',
                'unit_id' => 1,
                'category_id' => 2,
                'supplier_id' => 7,
                'price_per_unit' => 25000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kacang Panjang',
                'slug' => 'kacang-panjang',
                'unit_id' => 1,
                'category_id' => 2,
                'supplier_id' => 8,
                'price_per_unit' => 7000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bayam',
                'slug' => 'bayam',
                'unit_id' => 1,
                'category_id' => 2,
                'supplier_id' => 9,
                'price_per_unit' => 6000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bawang Daun',
                'slug' => 'bawang-daun',
                'unit_id' => 1,
                'category_id' => 2,
                'supplier_id' => 10,
                'price_per_unit' => 8000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === Kategori 3: Bumbu ===
            [
                'name' => 'Bawang Merah',
                'slug' => 'bawang-merah',
                'unit_id' => 1,
                'category_id' => 3,
                'supplier_id' => 1,
                'price_per_unit' => 32000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bawang Putih',
                'slug' => 'bawang-putih',
                'unit_id' => 1,
                'category_id' => 3,
                'supplier_id' => 2,
                'price_per_unit' => 28000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cabe Merah',
                'slug' => 'cabe-merah',
                'unit_id' => 1,
                'category_id' => 3,
                'supplier_id' => 3,
                'price_per_unit' => 40000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lengkuas',
                'slug' => 'lengkuas',
                'unit_id' => 1,
                'category_id' => 3,
                'supplier_id' => 4,
                'price_per_unit' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jahe',
                'slug' => 'jahe',
                'unit_id' => 1,
                'category_id' => 3,
                'supplier_id' => 5,
                'price_per_unit' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kunyit',
                'slug' => 'kunyit',
                'unit_id' => 1,
                'category_id' => 3,
                'supplier_id' => 6,
                'price_per_unit' => 18000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === Kategori 4: Minuman ===
            [
                'name' => 'Susu Cair',
                'slug' => 'susu-cair',
                'unit_id' => 2,
                'category_id' => 4,
                'supplier_id' => 7,
                'price_per_unit' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sirup Rasa Melon',
                'slug' => 'sirup-melon',
                'unit_id' => 2,
                'category_id' => 4,
                'supplier_id' => 8,
                'price_per_unit' => 18000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kopi Bubuk',
                'slug' => 'kopi-bubuk',
                'unit_id' => 3,
                'category_id' => 4,
                'supplier_id' => 9,
                'price_per_unit' => 90000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Teh Celup',
                'slug' => 'teh-celup',
                'unit_id' => 4,
                'category_id' => 4,
                'supplier_id' => 10,
                'price_per_unit' => 12000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gula Cair',
                'slug' => 'gula-cair',
                'unit_id' => 2,
                'category_id' => 4,
                'supplier_id' => 1,
                'price_per_unit' => 16000,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === Kategori 5: Bahan Pokok ===
            [
                'name' => 'Beras Premium',
                'slug' => 'beras-premium',
                'unit_id' => 1,
                'category_id' => 5,
                'supplier_id' => 2,
                'price_per_unit' => 14000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gula Pasir',
                'slug' => 'gula-pasir',
                'unit_id' => 1,
                'category_id' => 5,
                'supplier_id' => 3,
                'price_per_unit' => 16000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Minyak Goreng',
                'slug' => 'minyak-goreng',
                'unit_id' => 2,
                'category_id' => 5,
                'supplier_id' => 4,
                'price_per_unit' => 22000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tepung Terigu',
                'slug' => 'tepung-terigu',
                'unit_id' => 1,
                'category_id' => 5,
                'supplier_id' => 5,
                'price_per_unit' => 13000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Garam Halus',
                'slug' => 'garam-halus',
                'unit_id' => 1,
                'category_id' => 5,
                'supplier_id' => 6,
                'price_per_unit' => 8000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
